- name: Ansible apt module examples
  hosts: targetx
  become: yes
  tasks:
    - include_vars: vars.yml
   
        
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'libpq-dev']
      
      
    - name: Install  python package
      pip:
       name: psycopg2


        
    - name: ping postgres
      postgresql_ping:
         db: '{{ DbName }}'
         login_host: '{{ DBendpoint }}'
         login_password: '{{ MasterDbPassword }}'
         login_user: '{{ MasterDbUser }}' 
    - name: add db
      postgresql_db:
       login_host: '{{ DBendpoint }}'
       login_password: '{{ MasterDbPassword }}'
       login_user: '{{ MasterDbUser }}' 
       name: validator_backend
       
       
    - name: add user
      postgresql_user:
       db: '{{ DbName }}'
       login_host: '{{ DBendpoint }}'
       login_password: '{{ MasterDbPassword }}'
       login_user: '{{ MasterDbUser }}'  
       name: '{{ DbUser }}' 
       priv: "CONNECT/CREATE"
       password: '{{ DbPassword }}'
     

    - name: set privliages
      postgresql_privs:
       db: '{{ DbName }}'
       login_host: '{{ DBendpoint }}'
       login_password: '{{ MasterDbPassword }}'
       login_user: '{{ MasterDbUser }}'   
       role: '{{ DbUser }}' 
       objs: ALL_IN_SCHEMA
       priv: SELECT,INSERT,UPDATE,DELETE



    - name: download latest sql file
      command: "wget https://raw.githubusercontent.com/hussein8595/pg-demo/master/sample.sql"
      become: yes
      args:
       chdir: /opt
       
    - name: Run queries from SQL script
      postgresql_query:
       db: '{{ DbName }}'
       login_host: '{{ DBendpoint }}'
       login_password: '{{ DbPassword }}'
       login_user: '{{ DbUser }}' 
       path_to_script: /opt/sample.sql
       
        
    - name: delete sql file 
      command: "rm sample.sql"
      become: yes
      args:
       chdir: /opt



